spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:data
    username: root
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 30000
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
      # 默认开启，当前已开启
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
      # 默认关闭，需手动开启，当前已开启
      slf4j:
        enabled: true
        data-source-log-enabled: false
        connection-log-enabled: false
        statement-log-enabled: false
        result-set-log-enabled: false
      # 默认关闭，需手动开启，当前已开启
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        config:
          delete-where-none-check: true
      # 默认关闭，需手动开启，当前已关闭
      config:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      web-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      aop-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      stat-view-servlet:
        enabled: false
  transaction:
    rollback-on-commit-failure: true
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      write_null_map_values: true
      write_dates_as_timestamps: false
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.hyp.learn.data.entity
  configuration:
    #自动驼峰命名规则( camel case )映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-prefix: executableSql.
logging:
  level:
    root: info
    org.springframework: info
    org.springframework.jdbc: debug
    org.springframework.boot: info
    org.mybatis: debug
    com.alibaba.druid: debug
    com.github.trang: debug
    executableSql: debug
server:
  servlet:
    context-path: /data