spring:
  datasource:
    url: jdbc:h2:mem:shiro
    username: root
    password: root
    driver-class-name: org.h2.Driver
    data: database/import.sql
#    schema: database/schema.sql

  jpa:
    database: h2
    show-sql: true
    hibernate:
#      ddl-auto: update


  thymeleaf:
    cache: false
    mode: LEGACYHTML5